//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TChoice
    {
        public int ID { get; set; }
        public int FK_TQuestion_ID { get; set; }
        public string Choice { get; set; }
        public int Votes { get; set; }
    
        public virtual TQuestion TQuestion { get; set; }
    }
}
